apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysqldb
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: myapp
      labels:
        app: mysql
    spec:
      containers:
      - name: mysqlcont
        image: mysql
        #ports:
        #- containerPort: 27017
        env:
        - name: WORDPRESS_DB_USERNAME
          value: worduser
        - name: WORDPRESS_DB_PASSWORD
          value: wordpass
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlservice
spec:
  type: ClusterIP
  selector:
    app: mysql
  #ports:
  #- port: 27017
  #  targetPort: 27017