apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordeply
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpresscont
        image: wordpress
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value:  mysqlservice
        - name: WORDPRESS_DB_USER
          value: worduser
        - name: WORDPRESS_DB_PASSWORD
          value: wordpass
        - name: WORDPRESS_DB_NAME
          value: mysqldb
---
apiVersion: v1
kind: Service
metadata:
  name: wordsvc
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
